config/routes.rb
Rails.application.routes.draw do
  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end

  get '/', to: redirect('/swagger')

end

app/views/shares/_header.html.slim
ul.nav.navbar-top-links.navbar-right
  - if user_signed_in?
    li= current_user.email
  /! /.dropdown
  li.dropdown
    a.dropdown-toggle data-toggle="dropdown" href="#"
      i.fa.fa-user.fa-fw
      i.fa.fa-caret-down
    ul.dropdown-menu.dropdown-user
      li
        a href="#"
          i.fa.fa-user.fa-fw
          | User Profile
      li
        a href="#"
          i.fa.fa-gear.fa-fw
          | Settings
      li.divider
      li
        = link_to( destroy_user_session_path, :method => :delete) do
          i.fa.fa-sign-out.fa-fw
          | Logout
    /! /.dropdown-user
  /! /.dropdown

app/views/shares/_sidebar.html.slim
.navbar-default.sidebar role="navigation"
  .sidebar-nav.navbar-collapse
    ul#side-menu.nav
      li.sidebar-search
        .input-group.custom-search-form
          input.form-control placeholder="Search..." type="text" /
          span.input-group-btn
            button.btn.btn-default type="button"
              i.fa.fa-search
        /! /input-group
      li
        = link_to categories_path do
          i.fa.fa-table.fa-fw
          | Categories
      li
        = link_to beers_path do
          i.fa.fa-edit.fa-fw
          | Beers
      li
        a href="#"
          i.fa.fa-bar-chart-o.fa-fw
          | Admin Members
          span.fa.arrow
        ul.nav.nav-second-level
          li
            = link_to "List", users_path
          li
            = link_to "Add new", new_user_path
        /! /.nav-second-level
  /! /.sidebar-collapse
/! /.navbar-static-side