config/routes.rb
Rails.application.routes.draw do
  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end

  get '/', to: redirect('/swagger')

end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10

  acts_as_paranoid

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  #:registerable

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true, uniqueness: true

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
    layout false

    # GET /resource/password/new
    def new
      super
    end

    # POST /resource/password
    def create
      super
    end

    # GET /resource/password/edit?reset_password_token=abcdef
    def edit
      super
    end

    # PUT /resource/password
    def update
      super
    end

    # protected

    def after_resetting_password_path_for(resource)
      super(resource)
    end

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      super(resource_name)
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    layout false

    before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    def new
      super
    end

    # POST /resource/sign_in
    def create
      super
    end

    # DELETE /resource/sign_out
    def destroy
      super
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_in_params
      devise_parameter_sanitizer.for(:sign_in) << :attribute
    end
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.page params[:page]
  end

  # GET /users/1
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    # to do for generate pass and send mail
    if @user.save
      redirect_to users_url, notice: 'Member was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_url, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Member was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    permited_params = params.require(:user).permit(:name, :email, :address)
    permited_params.merge!(password: '12345678')
  end
end

app/views/users/_form.html.slim
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      ul.alert.alert-danger
        - @user.errors.full_messages.each do |message|
          li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :address
    = f.text_field :address, class: "form-control"
  .actions
    = f.submit "Submit", class: "btn btn-primary"

app/views/users/_modal_show.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" style=("display: none;") tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4#myModalLabel.modal-title
      .modal-body
        table
          tbody
            tr
              td
                strong Email: 
              td#email
            tr
              td colspan="3"
                strong Address:
                p#address
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close

app/views/users/_user.html.slim
tr
  td
    = user.id
  td
    = user.try(:name)
  td
    = user.try(:email)
  td
    = truncate user.try(:address), length: 160
  td
    = link_to "Show", user, :class => "", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal"
    |  |
    = link_to 'Edit', edit_user_path(user)
    |  |
    = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/edit.html.slim
h1 Editing User
= render 'form'

app/views/users/index.html.slim
h1.page-header Listing Admin Members
- if notice
  .alert.alert-success
    = notice
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading Table
      .panel-body
        .table-responsive
          table.table.table-striped.table-bordered.table-hover
            thead
              tr
                th.col-lg-1.text-center #
                th.col-lg-2.text-center Name
                th.col-lg-3.text-center Email
                th.col-lg-4.text-center Address
                th.col-lg-2.text-center Action
            tbody
              = render partial: "user", collection: @users
#category-modal
  = render "modal_show"
.row
  .pull-left
    .text-center
      = paginate @users, :theme => 'twitter-bootstrap-3'
  .pull-right.pagination
    = link_to 'New User', new_user_path, class: "btn btn-default"

app/views/users/new.html.slim
h1.page-header New User
= render 'form'

app/views/users/show.js.erb
$("#category-modal .modal-title").html("<%= @user.name %>");
$("#category-modal .modal-body #email").html("<%= @user.email %>");
$("#category-modal .modal-body #address").html("<%= @user.address %>");