config/routes.rb
Rails.application.routes.draw do
  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end

  get '/', to: redirect('/swagger')

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  paginates_per 10

  acts_as_paranoid

  belongs_to :category

  validates :name, presence: true
  validates :category_id, presence: true
  validates :manufacturer, presence: true
  validates :country, presence: true
  validates :price, presence: true, format: { :with => /\A\d+(?:\.\d{0,2})?\z/ }, numericality: {:greater_than => 0}
  validates :description, presence: true

  scope :beers_of_category, ->(category_id) { where(category_id: category_id) }
  scope :archived, ->{ where( archive_status: 1) }
  scope :unarchived, ->{ where( archive_status: 0) }
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :beer, only: [:show, :edit, :update, :destroy, :archive, :unarchive]
  before_action :categories, only: [:new, :edit, :create, :update]

  # GET /beers
  def index
    @beers = Beer.order(id: :desc).page params[:page]
  end

  # GET /beers/1
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  def create
    @beer = Beer.new(beer_params)
    if @beer.save
      redirect_to beers_url, notice: 'Beer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /beers/1
  def update
    if @beer.update(beer_params)
      redirect_to beers_url, notice: 'Beer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /beers/1
  def destroy
    @beer.destroy
    redirect_to beers_url, notice: 'Beer was successfully destroyed.'
  end

  # PUT beers/1/archive
  def archive
    if @beer.update(archive_status: 1)
      redirect_to :back, notice: 'Beer was successfully archived.'
    else
      redirect_to beers_url, notice: 'Beer was not successfully archived.'
    end
  end

  # PUT beers/1/unarchive
  def unarchive
    if @beer.update(archive_status: 0)
      redirect_to :back, notice: 'Beer was successfully unarchived.'
    else
      redirect_to beers_url, notice: 'Beer was not successfully unarchived.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def beer
    @beer = Beer.includes(:category).find(params[:id])
  end

  def categories
    @categories = Category.pluck(:name, :id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_params
    permited_params = params.require(:beer).permit(:name, :manufacturer, :country, :price, :description)
    permited_params.merge!(category: Category.find_by(id: params[:beer][:category_id]))
  end
end

app/views/beers/_beer.html.slim
tr
  td
    = beer.id
  td
    = beer.name
  td
    = beer.manufacturer
  td
    = beer.country
  td
    = beer.price ? number_to_currency(beer.price, :precision => 2) : number_to_currency(0)
  td
    = link_to "Show", beer, :class => "", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal"
    |  |
    = link_to 'Edit', edit_beer_path(beer)
    |  |
    - if beer.archive_status == 1
      = link_to 'Unarchive', unarchive_beer_path(beer), method: :put, data: { confirm: 'Are you sure, you wanna unarchive this beer?' }
    - else
      = link_to 'Archive', archive_beer_path(beer), method: :put, data: { confirm: 'Are you sure, you wanna archive this beer?' }
    |  |
    = link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' }

app/views/beers/_form.html.slim
= form_for(@beer) do |f|
  - if @beer.errors.any?
    #error_explanation
      ul.alert.alert-danger
        - @beer.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :category
    = f.select :category_id, @categories ,{include_blank: true}, {class: "form-control"}
  .form-group
    = f.label :manufacturer
    = f.text_field :manufacturer, class: "form-control"
  .form-group
    = f.label :country
    = f.text_field :country, class: "form-control"
  .form-group
    = f.label :price
    = f.number_field :price, class: "form-control", :step => 'any'
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control", rows: "5"
  .actions
    = f.submit "Submit", class: "btn btn-primary"

app/views/beers/_modal_show.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" style=("display: none;") tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4#myModalLabel.modal-title
      .modal-body
        table
          tbody
            tr
              td
                strong Category: 
              td#category
            tr
              td
                strong Country: 
              td#country
            tr
              td
                strong Manufacturer: 
              td#manufacturer
            tr
              td
                strong Price: 
              td#price
            tr
              td colspan="3"
                strong Description:
                p#description
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close

app/views/beers/edit.html.slim
h1 Editing Beer
= render 'form'

app/views/beers/index.html.slim
h1.page-header Listing Beers
- if notice
  .alert.alert-success
    = notice
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading Table
      .panel-body
        .table-responsive
          table.table.table-striped.table-bordered.table-hover
            thead
              tr
                th.col-lg-1.text-center #
                th.col-lg-2.text-center Name
                th.col-lg-2.text-center Manufacturer
                th.col-lg-2.text-center Country
                th.col-lg-1.text-center Price
                th.col-lg-3.text-center Action
            tbody
              = render partial: "beer", collection: @beers
#category-modal
  = render "modal_show"
.row
  .pull-left
    .text-center
      = paginate @beers, :theme => 'twitter-bootstrap-3'
  .pull-right.pagination
    = link_to 'New Beer', new_beer_path, class: "btn btn-default"

app/views/beers/new.html.slim
h1.page-header New Beer
= render 'form'

app/views/beers/show.js.erb
$("#category-modal .modal-title").html("<%= @beer.name %>");
$("#category-modal .modal-body #country").html("<%= @beer.country %>");
$("#category-modal .modal-body #manufacturer").html("<%= @beer.manufacturer %>");
$("#category-modal .modal-body #price").html("<%= @beer.price ? number_to_currency(@beer.price, :precision => 2) : number_to_currency(0) %>");
$("#category-modal .modal-body #category").html("<%= @beer.category.name %>");
$("#category-modal .modal-body #description").html("<%= @beer.description %>");