config/routes.rb
Rails.application.routes.draw do
  mount CoreAPI => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  scope :admin do
    root 'dashboards#index'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    resources :users
    resources :beers do
      put 'archive', on: :member
      put 'unarchive', on: :member
    end
    resources :categories
  end

  get '/', to: redirect('/swagger')

end

app/models/category.rb
class Category < ActiveRecord::Base
  paginates_per 10

  acts_as_paranoid

  has_many :beers, dependent: :restrict_with_error

  has_many :unarchived_beers, -> { where archive_status: 0 }, class_name: 'Beer'

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.order(id: :desc).page params[:page]
  end

  # GET /categories/1
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.' if @category.destroy
    redirect_to categories_url, notice: 'Cannot delete record because of `dependent beers'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/views/categories/_category.html.slim
tr
  td = category.id
  td = category.name
  td = truncate category.description, length: 160
  td
    = link_to "Show", category, :class => "", :remote => true, "data-toggle" => "modal", "data-target" => "#myModal"
    | |
    = link_to 'Edit', edit_category_path(category)
    | |
    = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

app/views/categories/_form.html.slim
= form_for(@category) do |f|
  - if @category.errors.any?
    #error_explanation
      ul.alert.alert-danger
        - @category.errors.full_messages.each do |message|
          li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control", rows: "5"
  .actions
    = f.submit "Submit", class: "btn btn-primary"

app/views/categories/_modal_show.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" style=("display: none;") tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4#myModalLabel.modal-title
      .modal-body
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close
    /! /.modal-content
  /! /.modal-dialog

app/views/categories/edit.html.slim
h1.page-header Editing Category
= render 'form'

app/views/categories/index.html.slim
h1.page-header Listing Categories
- if notice
  .alert.alert-success= notice
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading Table
      .panel-body
        .table-responsive
          table.table.table-striped.table-bordered.table-hover
            thead
              tr
                th.col-lg-1.text-center #
                th.col-lg-3.text-center Name
                th.col-lg-6.text-center Description
                th.col-lg-2.text-center Action
            tbody
              = render partial: "category", collection: @categories
#category-modal
  = render "modal_show"
.row
  .pull-left
    .text-center
      = paginate @categories, :theme => 'twitter-bootstrap-3'
  .pull-right.pagination
    = link_to 'New Category', new_category_path, class: "btn btn-default"

app/views/categories/new.html.slim
h1.page-header New Category
= render 'form'

app/views/categories/show.js.erb
$("#category-modal .modal-title").html("<%= @category.name %>");
$("#category-modal .modal-body").html("<%= @category.description %>");